name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build code
        run: npm run build
      - name: Test code
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E-Test code
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notification Success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: Pokedex-Notifier
          color: '#20ff11'
          description: to https://full-stack-open-pokedex-gzkj.onrender.com/ by ${{ github.actor }}
          footer: 'Severity: Informational'
          text: A new version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notification Failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          username: Pokedex-Notifier
          color: '#ff2011'
          description: commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build :(
          footer: 'Severity: Error'
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notification Cancel
        if: ${{ cancelled() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          username: Pokedex-Notifier
          color: '#fac400'
          description: Test and deployment cancelled
          footer: 'Severity: Warning'
          text: Build cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
